### ISSUE TITLE
mysqldump not showing correctly progress using node and jv

### ISSUE THREAD

**Issue by ronovar** [juliangruber/node-pv#12]
I im using this code:

    var pv = PV({
        size: 5.4m,
    	name: mysqlbackup
    })
    	
    pv.on('info', function(str){
    	console.log('progress...'+str)
    })
    			
    process.stdin.pipe(pv).pipe(process.stdout);
    		
    /* DUMP - database */
    var mysqldump = child_process.exec(['mysqldump -u root --password=mydatabasepass databasename | zip --password myzipassword | pv --progress --size 5.4m > '+process.env.PWD+'/mysqlbackup-'+date+'.zip']);

i im using this node library:

    https://www.npmjs.com/package/node-pv

and created zip file is 0KB and this is from terminal output:

    dumpmybase:  0B  00:00:01  [0B/s]  NaN%
    dumpmybase:  0B  00:00:02  [0B/s]  NaN%
    dumpmybase:  0B  00:00:03  [0B/s]  NaN%
    dumpmybase:  0B  00:00:04  [0B/s]  NaN%
    dumpmybase:  0B  00:00:05  [0B/s]  NaN%
    dumpmybase:  0B  00:00:06  [0B/s]  NaN%
    dumpmybase:  0B  00:00:07  [0B/s]  NaN%
    dumpmybase:  0B  00:00:08  [0B/s]  NaN%

and so on...the dump file is empty and i get this progress of all zero...i need to get only percentage of progress so that i can later send ajax on progress bar to show client progress of creating backup and later importing sql dump file.

SO what i im doing wrong? i read api of node-jv but i coul't not figure out why this does not work...

**Comment by juliangruber** [comment]
Why are you using this module's CLI _and_ API? Just one of them should be enough.

Try this:

```bash
$ npm install -g node-pv
$ mysqldump -u root --password=mydatabasepass databasename | zip --password myzipassword | pv --size 56623104 --name dumpmybase > ./mysqlbackup.zip
```

I don't know where you got the `--progress` argument from, also `--size` is in bytes.

**Comment by ronovar** [comment]
Thanks fore replaying..it make sense now...using just one module and that will be node-pv API...but i don't know where in node-pv API i put link with complete mysqldump command?

I think if is possible or is other way to put mysqldump command to node-pv like this:

var pv = PV({
    size: 5.4m,
    name: mysqlbackup,
    url: 'mysqldump -u root --password=mydatabasepass databasename | zip --password myzipassword | pv --size 56623104 --name dumpmybase > ./mysqlbackup.zip';
})

And then using:

process.stdin.pipe(pv).pipe(process.stdout);

I will get output of percentage...--progress argument is from pv --help manual also --size it si replacement to -p and -s.

So if you could write me where i put mysqldump command to PV so that i can get correct output from PV?

**Comment by juliangruber** [comment]
This should do it:

```js
const dump = spawn('mysqldump', ['...'])
const pv = PV(...).on('info', ...)
dump.stdout.pipe(pv)
```

**Comment by ronovar** [comment]
Thanks but i have error in terminal:

mysqldump: Could't find table: ">"

I try using this code:

/* DUMP - database */
var mysqldump = spawn('mysqldump', ['-u', 'root', '-p'+db_pass, db_name, '>', process.env.PWD+'/'+results[Object.keys(results)[0]]+'-'+date+'.sql']);

i see the problem is '>' that is needed to specify where to save output file..because i need it to save it on disk and later i will add to zip it...so how to specify in spawn parameters output file location?

Reading into memory and then back to HDD is not good solution so if is possible to pass parameter in spawn to specify output file creation on HDD

**Comment by juliangruber** [comment]
This is a question related to nodejs streams and child processes, and not this library. So I'm going to close this.

As a hint:

```js
const dump = spawn('mysqldump', [...])
const zip = spawn('zip', [...])
const pv = PV({ ... })
const file = fs.createWriteStream('./result.sql')

dump.stdout.pipe(zip.stdin)
zip.stdout.pipe(pv)
pv.pipe(file)
```
